FROM ollama/ollama:latest

RUN apt-get update && apt-get install -y curl && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh
ENV GIN_MODE=release

ENTRYPOINT ["/app/entrypoint.sh"]